const assert = require('node:assert/strict');
const esbuild = require('esbuild');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
(async () => {
 const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'connectivity-'));
 await esbuild.build({stdin:{contents:"export * from './src/connectivity/connectivityStore'; export * from './src/authModeState';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',outfile:path.join(dir,'test.cjs')});
 const m = require(path.join(dir,'test.cjs'));
 let passed = 0;
 const check = (name, fn) => { fn(); passed++; console.log('PASS:',name); };
 const win = new EventTarget(), doc = new EventTarget(); doc.visibilityState='visible';
 global.window=win; global.document=doc;
 Object.defineProperty(global,'navigator',{value:{onLine:true},configurable:true});
 const onlineStore = m.createConnectivityStore(m.createBrowserConnectivityProvider(), m.readBrowserConnectivity());
 check('initial online seed',()=>assert.equal(onlineStore.getSnapshot(),true));
 navigator.onLine=false;
 const store = m.createConnectivityStore(m.createBrowserConnectivityProvider(), m.readBrowserConnectivity());

 check('initial offline',()=>assert.equal(store.getSnapshot(),false));
 let a=0,b=0;
 const offA=store.subscribe(()=>a++), offB=store.subscribe(()=>b++);
 navigator.onLine=true;win.dispatchEvent(new Event('online'));
 check('offline to online / multiple subscribers',()=>{assert.equal(store.getSnapshot(),true);assert.equal(a,1);assert.equal(b,1);});
 win.dispatchEvent(new Event('online'));
 check('duplicate event',()=>assert.equal(a,1));
 navigator.onLine=false;win.dispatchEvent(new Event('offline'));
 check('online to offline',()=>assert.equal(store.getSnapshot(),false));
 offA();navigator.onLine=true;win.dispatchEvent(new Event('online'));
 check('unsubscribe',()=>{assert.equal(a,2);assert.equal(b,3);});
 navigator.onLine=false;doc.dispatchEvent(new Event('visibilitychange'));
 check('foreground reconcile',()=>assert.equal(store.getSnapshot(),false));
 navigator.onLine=true;win.dispatchEvent(new Event('focus'));
 check('focus reconcile',()=>assert.equal(store.getSnapshot(),true));
 offB();win.dispatchEvent(new Event('offline'));
 check('cleanup',()=>assert.equal(b,5));
 let installs=0,removes=0,emit,refresh,resolve;
 const provider={readStatus:()=>new Promise(r=>resolve=r),subscribe:(e,r)=>{installs++;emit=e;refresh=r;return()=>removes++;}};
 const asyncStore=m.createConnectivityStore(provider);
 const off1=asyncStore.subscribe(()=>{}), off2=asyncStore.subscribe(()=>{});
 check('single provider subscription',()=>assert.equal(installs,1));
 emit(false);resolve(true);await Promise.resolve();
 check('stale initial result rejected',()=>assert.equal(asyncStore.getSnapshot(),false));
 refresh();emit(true);resolve(false);await Promise.resolve();
 check('stale foreground result rejected',()=>assert.equal(asyncStore.getSnapshot(),true));
 off1();off2();const off3=asyncStore.subscribe(()=>{});
 check('StrictMode-like lifecycle',()=>{assert.equal(installs,2);assert.equal(removes,1);});
 off3();
 const failed=m.createConnectivityStore({readStatus:()=>Promise.reject(Error('unavailable')),subscribe:()=>()=>{}},false);
 const stop=failed.subscribe(()=>{});await Promise.resolve();await Promise.resolve();
 check('lookup failure preserves state',()=>assert.equal(failed.getSnapshot(),false));stop();
 delete global.window;delete global.document;delete global.navigator;
 check('missing browser globals',()=>{const s=m.createConnectivityStore(m.createBrowserConnectivityProvider());assert.equal(s.getSnapshot(),true);s.subscribe(()=>{})();});
 m.setAuthModeState('offline-restored');
 const authStore=m.createConnectivityStore({readStatus:()=>true,subscribe:e=>{emit=e;return()=>{};}});
 const stopAuth=authStore.subscribe(()=>{});emit(false);emit(true);
 check('transport does not authorize cloud',()=>{assert.equal(m.isCloudSyncAllowed(),false);assert.equal(m.getAuthMode(),'offline-restored');});stopAuth();
 let reads=0, callback;
 const identity=m.connectivityStore;
 m.connectivityStore.configureProvider({readStatus:()=>{reads++;return false;},subscribe:e=>{callback=e;return()=>{};}},true);
 check('registration preserves identity and does not read provider',()=>{assert.equal(m.connectivityStore,identity);assert.equal(reads,0);});
 for(let i=0;i<20;i++){m.connectivityStore.getSnapshot();m.isTransportOnline();}
 check('getters before activation are pure',()=>assert.equal(reads,0));
 const release=m.connectivityStore.subscribe(()=>{});
 for(let i=0;i<20;i++){m.connectivityStore.getSnapshot();m.isTransportOnline();}
 check('active getters are pure',()=>{assert.equal(reads,1);assert.equal(m.isTransportOnline(),false);});
 check('active provider replacement rejected',()=>assert.throws(()=>identity.configureProvider(provider,true),/before first activation/));
 let transitions=[];let previous=identity.getSnapshot();
 const listen=()=>identity.subscribe(()=>{const next=identity.getSnapshot();if(next!==previous){previous=next;transitions.push(next);}});
 const unlisten=listen();callback(true);callback(true);callback(false);callback(true);
 check('rapid callback transitions deduplicated',()=>assert.deepEqual(transitions,[true,false,true]));
 unlisten();callback(false);previous=identity.getSnapshot();const relisten=listen();callback(true);relisten();
 check('callback resubscription',()=>assert.deepEqual(transitions,[true,false,true,true]));
 release();const last=m.isTransportOnline();
 for(let i=0;i<20;i++){assert.equal(identity.getSnapshot(),last);m.isTransportOnline();}
 check('getters after cleanup are pure',()=>assert.equal(reads,1));
 check('registration after first activation rejected even after cleanup',()=>assert.throws(()=>identity.configureProvider(provider,true),/before first activation/));
 console.log(`${passed} connectivity checks passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
