const assert = require('node:assert/strict');
const esbuild = require('esbuild');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
(async () => {
 const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sync-display-'));
 await esbuild.build({entryPoints:['src/capture/syncDisplayState.ts'],bundle:true,platform:'node',format:'cjs',outfile:path.join(dir,'display.cjs')});
 const {deriveLeadSyncDisplayState: derive,deriveQueueSyncSummary: summary,hasAutomaticRetryMetadata: retry} = require(path.join(dir,'display.cjs'));
 let count=0;
 const check=(name,fn)=>{fn(); count++;console.log('PASS:',name);};
 const lead={id:'local',backendSessionId:'remote',ownerId:'owner',status:'pending_sync',source:'completed'};
 const ops=[{ownerId:'owner',sessionId:'remote'}];
 const state=(l=lead,o=ops,online=true,auth='online')=>derive(l,o,'owner',online,auth);
 check('offline saved',()=>assert.equal(state(lead,ops,false),'Saved offline'));
 check('auth restricted with transport online',()=>{for(const auth of ['offline-restored','unauthenticated']) assert.equal(state(lead,ops,true,auth),'Saved offline');});
 check('online matching operation',()=>assert.equal(state(),'Syncing…'));
 check('online drained unfinished',()=>assert.equal(state(lead,[]),'Saved'));
 check('synced stays synced offline with leftover ops',()=>assert.equal(state({...lead,status:'synced'},ops,false),'Synced'));
 check('terminal exhausted failure',()=>assert.equal(state({...lead,status:'failed',isExhausted:true}),'Needs attention'));
 check('retryable failure without processing proof stays Saved',()=>assert.equal(state({...lead,status:'failed',isExhausted:false},[]),'Saved'));
 check('many ops still one lead state',()=>assert.equal(state(lead,Array(6).fill(ops[0])),'Syncing…'));
 check('unrelated session ignored',()=>assert.equal(state(lead,[{ownerId:'owner',sessionId:'other'}]),'Saved'));
 check('wrong op owner ignored',()=>assert.equal(state(lead,[{ownerId:'other',sessionId:'remote'}]),'Saved'));
 check('wrong lead owner ignored',()=>assert.equal(state({...lead,ownerId:'other'}),'Saved'));
 check('missing owner never matches',()=>assert.equal(state({...lead,ownerId:null}),'Saved'));
 check('legacy frontend session fallback',()=>assert.equal(state({...lead,backendSessionId:null},[{ownerId:'owner',sessionId:'local'}]),'Syncing…'));
 check('backend ID takes precedence over different frontend ID',()=>assert.equal(state(lead,[{ownerId:'owner',sessionId:'local'}]),'Saved'));
 check('missing session cannot match empty op',()=>assert.equal(state({...lead,id:'',backendSessionId:null},[{ownerId:'owner',sessionId:''}]),'Saved'));
 check('drafts never processing',()=>{for(const source of ['draft','saved_draft']) assert.equal(state({...lead,source},[]),'Draft');assert.equal(state({...lead,status:'draft'},[]),'Draft');});
 check('needs review preserved',()=>assert.equal(state({...lead,status:'needs_review'}),'Needs Review'));
 check('voice pending keeps syncing; nonblocking transcription needs no op',()=>{assert.equal(state(lead,[{...ops[0],type:'upload_voice_note'}]),'Syncing…');assert.equal(state(lead,[]),'Saved');});
 check('mixed independent lead states and summary',()=>{const states=[state(),state({...lead,id:'b',backendSessionId:'b'})];assert.deepEqual(states,['Syncing…','Saved']);assert.equal(summary(states),'Syncing saved leads…');});
 check('offline summary',()=>assert.equal(summary(['Saved offline']),'Saved safely offline. Will sync automatically when connected.'));
 check('saved summary',()=>assert.equal(summary(['Saved']),'Saved leads'));
 check('no false summary for drafts or finished leads',()=>assert.equal(summary(['Draft','Synced','Needs attention','Needs Review']),null));
 check('pre-submission QR/card/manual records stay Saved',()=>{for(const captureMethod of ['QR','BUSINESS_CARD','MANUAL']) for(const status of ['local_only','pending_sync']) assert.equal(state({...lead,captureMethod,status},[]),'Saved');});
 check('unknown legacy status stays neutral',()=>assert.equal(state({...lead,status:'legacy'},[]),'Saved'));
 check('automatic retry copy requires concrete retry metadata',()=>{const failed={status:'failed',isExhausted:false,retries:1,lastAttemptAt:'2026-10-04T00:00:00Z',failedStage:'VERIFY_ASSETS',failedAt:null};assert.equal(retry(failed),true);for(const patch of [{retries:0},{lastAttemptAt:null},{failedStage:null},{isExhausted:true},{failedAt:'2026-10-04'},{status:'synced'}])assert.equal(retry({...failed,...patch}),false);assert.equal(retry({status:'failed'}),false);});
 // Synthetic observer scope checks. Real transactions are in test_syncDisplayObserver.cjs.
 await esbuild.build({entryPoints:['src/capture/db.ts'],bundle:true,platform:'node',format:'cjs',outfile:path.join(dir,'db.cjs')});
 const db = require(path.join(dir,'db.cjs')); let handler;
 global.indexedDB={open(){const req={result:{addEventListener(type,fn,capture){assert.equal(type,'complete');assert.equal(capture,true);handler=fn;}}};queueMicrotask(()=>req.onsuccess());return req;}};
 await db.openDB(); let calls=0;const off=db.subscribePendingOps(()=>calls++);
 const event=(mode,stores)=>({target:{mode,objectStoreNames:{contains:s=>stores.includes(s)}}});
 check('synthetic pending scope notifies',()=>{handler(event('readwrite',['pending_ops']));assert.equal(calls,1);});
 check('synthetic multi-store scope notifies',()=>{handler(event('readwrite',['completed_leads','pending_ops']));assert.equal(calls,2);});
 check('readonly and unrelated writes do not notify',()=>{handler(event('readonly',['pending_ops']));handler(event('readwrite',['assets']));assert.equal(calls,2);});
 check('unsubscribe and resubscribe',()=>{off();handler(event('readwrite',['pending_ops']));assert.equal(calls,2);const stop=db.subscribePendingOps(()=>calls++);handler(event('readwrite',['pending_ops']));assert.equal(calls,3);stop();});
 console.log(`${count} tests passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
