const assert=require('node:assert/strict'),esbuild=require('esbuild'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'reconnect-trace-'));
const tick=()=>new Promise(r=>setImmediate(r));
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
(async()=>{
 global.window={};
 const out=path.join(dir,'helper.cjs');await esbuild.build({entryPoints:['src/runtime/reconnectTimingTrace.ts'],bundle:true,platform:'node',format:'cjs',outfile:out});
 const m=require(out),api=window.__reconnectTimingTrace;let passed=0;
 function check(name,fn){fn();passed++;console.log('PASS:',name);}
 check('disabled by default',()=>{m.reconnectTrace('TRANSPORT_ONLINE');assert.deepEqual(api.get(),[]);});
 check('enable and monotonic sequence',()=>{const run=api.enable();m.reconnectTrace('TRANSPORT_ONLINE');m.reconnectTrace('FLUSH_START',{flushId:'flush-1'});const rows=api.get();assert.equal(rows[0].runId,run);assert.deepEqual(rows.map(r=>r.sequence),[1,2]);assert(rows[1].elapsedMs>=rows[0].elapsedMs);assert(!isNaN(Date.parse(rows[0].timestamp)));});
 check('only whitelisted metadata / sanitized codes and counts',()=>{m.reconnectTrace('OP_END',{sessionId:'S1',jobId:'S1',opId:'op1',outcome:'failed',reason:'email@example.com',opType:'upload_voice_note',access_token:'secret',session:{token:'secret'},email:'email@example.com',counts:{total:3,secret:1,remaining:NaN}});const row=api.get().at(-1);assert.equal(row.outcome,'failed');assert.equal(row.reason,undefined);assert.deepEqual(row.counts,{total:3});assert(!JSON.stringify(row).includes('secret'));assert(!JSON.stringify(row).includes('@'));m.reconnectTrace('SECRET_EVENT');assert.equal(api.get().length,3);});
 check('read returns isolated snapshot',()=>{api.get()[0].event='BAD';assert.equal(api.get()[0].event,'TRANSPORT_ONLINE');});
 check('bounded at 2000; sequence never resets on eviction',()=>{api.clear();for(let i=0;i<2100;i++)m.reconnectTrace('TRANSPORT_ONLINE');assert.equal(api.get().length,2000);assert.equal(api.get()[0].sequence,101);assert.equal(api.get().at(-1).sequence,2100);});
 check('clear starts fresh run; old async context excluded',()=>{const old=m.traceContext();api.clear();m.reconnectTrace('FLUSH_END',{},old);assert.equal(api.get().length,0);m.reconnectTrace('TRANSPORT_ONLINE');assert.equal(api.get()[0].sequence,1);assert.notEqual(api.get()[0].runId,old.runId);});
 check('metadata getters and clock failures never escape',()=>{assert.doesNotThrow(()=>m.reconnectTrace('OP_END',new Proxy({},{get(){throw Error('bad getter');}})));const old=global.performance;global.performance={now(){throw Error('clock');}};assert.doesNotThrow(()=>m.reconnectTrace('TRANSPORT_ONLINE'));assert.doesNotThrow(()=>m.traceElapsed());global.performance=old;});
 check('disable retains existing trace and blocks new events',()=>{const n=api.get().length;api.disable();m.reconnectTrace('TRANSPORT_ONLINE');assert.equal(api.get().length,n);api.clear();m.reconnectTrace('TRANSPORT_ONLINE');assert.equal(api.get().length,0);});
 // Execute the actual scheduler with fake time; assert its existing behavior is unchanged.
 const schedOut=path.join(dir,'scheduler.cjs');
 const mocks={processingQueueRepository:`export const claimNextJob=async()=>{global.h.claims++;return global.h.job;};export const updateJobState=async()=>{};export const markRetrying=async()=>{};`,recoveryService:`export const runRecovery=async()=>global.h.recovery;export const reconcileCompletedLeads=async()=>({synced:0,failures:0});`,worker:`export const processJob=async()=>{global.h.workers++;return global.h.work;};`,decisionEngine:`export const decide=()=>({newState:'COMPLETED'});`,completedLeadsStorage:`export const cleanupOldSyncedCompletedLeads=async()=>0;export const updateCompletedLeadStatus=async()=>true;`,runtimeDiagnostics:`export const isConsoleEnabled=()=>false;`,authModeState:`export const isCloudSyncAllowed=()=>global.h.auth;`,connectivityStore:`export const isTransportOnline=()=>global.h.online;`};
 await esbuild.build({stdin:{contents:"export * from './src/alpe/scheduler';export * from './src/runtime/reconnectTimingTrace';export {alpeLog} from './src/alpe/diagnostics';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',outfile:schedOut,plugins:[{name:'boundaries',setup(b){b.onResolve({filter:/.*/},a=>mocks[path.basename(a.path)]?{path:path.basename(a.path),namespace:'mock'}:undefined);b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:mocks[a.path]}));}}]});
 const timers=new Map();let timerId=0;const originalSet=global.setTimeout,originalClear=global.clearTimeout;global.setTimeout=(fn,ms)=>{const id=++timerId;timers.set(id,{fn,ms});return id;};global.clearTimeout=id=>timers.delete(id);
 const s=require(schedOut),trace=s.reconnectTimingTrace;trace.enable();const recovery=defer();global.h={auth:true,online:true,claims:0,workers:0,recovery:recovery.promise,job:null,work:{}};
 const starting=s.startScheduler('owner');s.notifyAlpeReconnect();assert.equal(h.claims,0);assert(trace.get().some(e=>e.event==='WAKE_IGNORED'&&e.reason==='starting'));recovery.resolve({});await starting;
 assert.equal(h.claims,0);assert.equal(timers.size,1);assert.equal([...timers.values()][0].ms,5000);passed++;console.log('PASS: recovery still precedes 5-second first poll; starting wake still ignored');
 s.notifyAlpeReconnect();await tick();assert.equal(h.claims,1);assert.equal(timers.size,1);let events=trace.get();const claimStart=events.find(e=>e.event==='CLAIM_START'),claimEnd=events.find(e=>e.event==='CLAIM_END');assert.equal(claimStart.tickId,claimEnd.tickId);assert.equal(claimEnd.outcome,'not_claimed');passed++;console.log('PASS: idle wake/empty claim traced without adding timers');
 const [scheduledId,scheduled]=timers.entries().next().value;timers.delete(scheduledId);scheduled.fn();await tick();assert.equal(h.claims,2);assert.equal(timers.size,1);assert.equal([...timers.values()][0].ms,5000);passed++;console.log('PASS: scheduled no-job tick still reschedules at 5 seconds');
 const work=defer();h.job={id:'S1',capture_session_id:'S1',retry_count:0};h.work=work.promise;s.notifyAlpeReconnect();await tick();s.notifyAlpeReconnect();assert.equal(h.workers,1);assert(trace.get().some(e=>e.event==='WAKE_IGNORED'&&e.reason==='busy'));work.resolve({});await tick();assert.equal(h.claims,3);passed++;console.log('PASS: busy wake still dropped; one worker, no coalesced follow-up');
 const before=h.claims;h.auth=false;s.notifyAlpeReconnect();await tick();assert.equal(h.claims,before);h.auth=true;h.online=false;s.notifyAlpeReconnect();await tick();assert.equal(h.claims,before);passed++;console.log('PASS: auth/transport gates unchanged');
 s.alpeLog('Worker start',{jobId:'S1',captureSessionId:'S1',token:'secret'});s.alpeLog('PROMOTION_SUCCESS',{captureSessionId:'S1',leadId:'L1',email:'secret'});assert(trace.get().some(e=>e.event==='WORKER_START'&&e.jobId==='S1'));assert(trace.get().some(e=>e.event==='PROMOTION_SUCCESS'&&e.sessionId==='S1'));assert(!JSON.stringify(trace.get()).includes('secret'));passed++;console.log('PASS: safe bridge works while broad diagnostics disabled');
 await s.stopScheduler();assert.equal(timers.size,0);global.setTimeout=originalSet;global.clearTimeout=originalClear;
 // Exercise production replay ordering and repository acknowledgments with tracing enabled.
 const queueOut=path.join(dir,'queue.cjs');
 const qMocks={
  db:`export const dbGetAllInStoreStrict=async()=>[...global.q.rows.values()];export const dbPutStrict=async(s,o)=>global.q.rows.set(o.id,o);export const dbDeleteStrict=async(s,id)=>global.q.rows.delete(id);`,
  captureBackendSync:['syncUpsertSession','syncUpsertAsset','syncUpsertOcrExtraction','syncUpsertQrExtraction','syncUpdateSessionFields','syncUpsertVisionExtraction','syncPromoteSession'].map(n=>`export const ${n}=async p=>{global.q.order.push('session:'+p.sessionId);};`).join(''),
  voiceOpStorage:`export const changeVoiceOp=async()=>true;`,voiceEvidenceManager:`export const executeVoiceNoteUploadOp=async()=>{};`,
  assetStorageUpload:`export const uploadBusinessCardAsset=async a=>{global.q.order.push('card:'+a.sessionId);return {uploaded:true,metadataWritten:true};};export const uploadNotesImage=async()=>{};export const reconcileAssetStorageMetadata=async()=>true;`,
  completedLeadsStorage:`export const buildCompletedLead=()=>({});export const saveQueuedCapture=async()=>{};`,
  jobProducer:`import {enqueueJob} from '${process.cwd()}/src/alpe/processingQueueRepository.ts';export const produceProcessingJob=async p=>{global.q.order.push('job:'+p.backendSessionId);const r=await enqueueJob({jobId:p.backendSessionId,captureSessionId:p.backendSessionId,userId:'u'});return {outcome:r.success?'queued':'failed',jobId:r.jobId};};`,
  supabaseClient:`export const supabase={from:()=>{let insert=false;const q={insert(){insert=true;return q;},select(){return q;},eq(){return q;},async maybeSingle(){if(global.q.throwRequest)throw Error('private server details');return {data:insert?(global.q.error?null:{id:'S1'}):{id:'S1'},error:insert?global.q.error:null};}};return q;}};`,
  authModeState:`export const isCloudSyncAllowed=()=>global.q.auth;`,connectivityStore:`export const isTransportOnline=()=>global.q.online;`,
  runtimeDiagnostics:`export const isConsoleEnabled=()=>false;`,
  assetSyncDiagnostics:['logOperationStart','logOperationEnd','logEvent','getCorrelationId'].map(n=>`export const ${n}=()=>{};`).join(''),
 };
 await esbuild.build({stdin:{contents:"export * from './src/capture/captureOfflineQueue';export * from './src/alpe/processingQueueRepository';export * from './src/runtime/reconnectTimingTrace';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',outfile:queueOut,plugins:[{name:'queue-boundaries',setup(b){b.onResolve({filter:/.*/},a=>qMocks[path.basename(a.path)]?{path:path.basename(a.path),namespace:'mock'}:undefined);b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:qMocks[a.path],resolveDir:process.cwd()}));}}]});
 const qa=require(queueOut);global.q={rows:new Map(),order:[],online:true,auth:true,error:null};qa.reconnectTimingTrace.enable();
 let opCount=0;for(const sessionId of ['S1','S2','S3'])for(const type of ['enqueue_processing_job','upload_business_card','upsert_session']){const id='op'+(++opCount);q.rows.set(id,{id,sessionId,ownerId:'u',type,createdAt:String(opCount).padStart(2,'0'),retries:0,payload:{sessionId,backendSessionId:sessionId,assetId:sessionId,ownerId:'u'}});}
 await qa.flushQueue('u');assert.deepEqual(q.order,['session:S1','session:S2','session:S3','card:S1','card:S2','card:S3','job:S1','job:S2','job:S3']);const qt=qa.reconnectTimingTrace.get();assert.equal(qt.filter(e=>e.event==='OP_START').length,9);assert.equal(qt.filter(e=>e.event==='OP_END').length,9);assert(qt.some(e=>e.event==='ENQUEUE_PHASE_REACHED'&&e.counts.remaining===0));assert.equal(new Set(qt.filter(e=>e.flushId).map(e=>e.flushId)).size,1);passed++;console.log('PASS: tracing preserves three-lead global replay barrier; paired operation timings');
 for(const [error,expected] of [[null,'inserted'],[{code:'23505'},'duplicate_recognized'],[{code:'403',message:'private'},'failed']]){q.error=error;await qa.enqueueJob({jobId:'S1',captureSessionId:'S1',userId:'u'});assert.equal(qa.reconnectTimingTrace.get().at(-1).outcome,expected);}
 q.throwRequest=true;await assert.rejects(qa.enqueueJob({jobId:'S1',captureSessionId:'S1',userId:'u'}),/private server details/);assert.equal(qa.reconnectTimingTrace.get().at(-1).outcome,'failed');assert(!JSON.stringify(qa.reconnectTimingTrace.get()).includes('private'));passed++;console.log('PASS: inserted/duplicate/failed/thrown acknowledgment outcomes without response data');
 q.throwRequest=false;q.online=false;await qa.flushQueue('u');assert.equal(qa.reconnectTimingTrace.get().at(-1).reason,'offline');q.online=true;q.auth=false;await qa.flushQueue('u');assert.equal(qa.reconnectTimingTrace.get().at(-1).reason,'auth_restricted');passed++;console.log('PASS: offline/auth-restricted skips remain unchanged and visible');
 console.log(`${passed} reconnect timing checks passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
