// B1 production context/storage/resolver tests; SDK and IDB boundaries are controlled.
const assert=require('node:assert/strict');
const esbuild=require('esbuild');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'event-cache-'));
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
const tick=()=>new Promise(r=>setImmediate(r));
const event=(id='EV-123',patch={})=>({id,event_code:'CODE-'+id,name:id,description:null,location:null,start_date:null,end_date:null,status:'ACTIVE',is_active:true,is_default:false,...patch});
const mocks={
 react:`export const createContext=()=>({Provider:'Provider'});export const useContext=()=>globalThis.value;export const useState=x=>globalThis.host.state(x);export const useRef=x=>globalThis.host.ref(x);export const useCallback=(f,d)=>globalThis.host.memo(f,d);export const useEffect=(f,d)=>globalThis.host.effect(f,d);`,
 'react/jsx-runtime':`export const jsx=(type,props)=>{if(type==='Provider')globalThis.value=props.value;return null;};export const jsxs=jsx;`,
 AuthContext:`export const useAuth=()=>globalThis.h.auth;`,
 authModeState:`export const isCloudSyncAllowed=()=>globalThis.h.auth.authMode==='online';`,
 connectivityStore:`export const isTransportOnline=()=>globalThis.h.online;`,
 supabaseClient:`export const supabase=globalThis.h.sdk;export const hasPersistedSupabaseSessionForUser=id=>id===globalThis.h.auth.user?.authUserId;`,
 db:`export const dbGet=async(s,k)=>{if(globalThis.h.readError)throw Error('IDB read');if(s==='event_cache'&&globalThis.h.readHold){const p=globalThis.h.readHold;globalThis.h.readHold=null;return await p;}return globalThis.h.db.get(s+k)||null;};export const dbPutStrict=async(s,row)=>{if(globalThis.h.writeError)throw Error('IDB write');globalThis.h.db.set(s+(s==='event_cache'?row.ownerId:row.key||row.id),structuredClone(row));};export const dbDeleteStrict=async()=>{};export const dbPut=dbPutStrict;export const dbDelete=async()=>{};export const dbGetAllInStore=async()=>[];`,
};
function host(){return {memo(f,d){let i=this.i++,old=this.slots[i];if(!old||d.some((x,j)=>x!==old.d[j]))this.slots[i]={d,value:f};return this.slots[i].value;},slots:[],i:0,todo:[],state(x){let i=this.i++;if(!(i in this.slots))this.slots[i]=x;return[this.slots[i],v=>{this.slots[i]=typeof v==='function'?v(this.slots[i]):v;}];},ref(x){let i=this.i++;return this.slots[i]??(this.slots[i]={current:x});},effect(f,d){let i=this.i++,old=this.slots[i];if(!old||d.some((x,j)=>x!==old.d[j]))this.todo.push(()=>{old?.cleanup?.();this.slots[i]={d,cleanup:f()};});},run(f){global.host=this;this.i=0;f();this.todo.splice(0).forEach(f=>f());},stop(){this.slots.forEach(x=>x?.cleanup?.());}};}
(async()=>{
 const out=path.join(dir,'actual.cjs');
 await esbuild.build({stdin:{contents:"export * from './src/EventContext';export * from './src/capture/eventCacheStorage';export * from './src/capture/authProfileStorage';export * from './src/capture/captureDraftStorage';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',jsx:'automatic',outfile:out,plugins:[{name:'boundaries',setup(b){b.onResolve({filter:/.*/},a=>{const k=mocks[a.path]?a.path:path.basename(a.path);if(mocks[k])return {path:k,namespace:'mock'};});b.onLoad({filter:/.*/,namespace:'mock'},a=>({contents:mocks[a.path],loader:'js'}));}}]});
 let passed=0;
 function setup(mode='online',db=new Map()){
  const h=global.h={db,online:mode==='online',list:[event()],queryError:null,repError:null,updates:[],filters:[],fetches:0,auth:{user:{authUserId:'A'},salesRep:{id:'rep-A',auth_user_id:'A',default_event_id:'EV-123'},authMode:mode}};
  h.auth.updateSalesRep=p=>{h.auth.salesRep={...h.auth.salesRep,...p};};
  h.sdk={from(table){let update=false;return {select(){return this;},eq(k,v){h.filters.push([k,v]);return this;},order(){h.fetches++;return h.fetchHold||Promise.resolve({data:h.queryError?null:h.list,error:h.queryError});},update(p){update=p;return this;},maybeSingle:async()=>({data:h.repError?null:{default_event_id:h.auth.salesRep.default_event_id},error:h.repError}),then(resolve){if(update)h.updates.push(update);return Promise.resolve({error:h.updateError||null}).then(resolve);}};}};
  delete require.cache[require.resolve(out)];const api=require(out),hooks=host();const render=()=>hooks.run(()=>api.EventProvider({children:null}));const settle=async()=>{for(let i=0;i<5;i++){render();await tick();}};return {h,api,hooks,render,settle};
 }
 async function test(name,fn){const f=setup();try{await fn(f);passed++;console.log('PASS:',name);}finally{f.hooks.stop();}}
 await test('B1.1/2 successful fetch, exact IDs and query predicates',async f=>{await f.settle();assert.equal(global.value.activeEvents[0].id,'EV-123');assert.equal((await f.api.loadEventCache('A'))[0].id,'EV-123');assert(f.h.filters.some(x=>x[0]==='status'&&x[1]==='ACTIVE'));assert(f.h.filters.some(x=>x[0]==='is_active'&&x[1]===true));});
 await test('B1.3 failed refresh retains cache',async f=>{await f.settle();f.h.queryError=Error('network');await global.value.loadActiveEvents();f.render();assert.equal(global.value.activeEvents.length,1);assert.equal((await f.api.loadEventCache('A')).length,1);});
 await test('B1.4 successful [] replaces cache',async f=>{await f.settle();f.h.list=[];await global.value.loadActiveEvents();f.render();assert.deepEqual(global.value.activeEvents,[]);assert.deepEqual(await f.api.loadEventCache('A'),[]);assert.equal(global.value.selectedEvent,null);});
 await test('active means boolean AND status; nonqualifying success is empty',async f=>{f.h.list=[event('x',{status:'UPCOMING'}),event('y',{is_active:false})];await f.settle();assert.deepEqual(await f.api.loadEventCache('A'),[]);assert.deepEqual(f.api.activeEventSnapshot([event(),...f.h.list]),[event()]);});
 await test('B1.5/7 offline cold context resolves cached profile default',async f=>{await f.settle();const db=f.h.db;f.hooks.stop();const cold=setup('offline-restored',db);await cold.settle();assert.equal(global.value.selectedEvent.id,'EV-123');assert.equal(cold.h.fetches,0);assert.equal(cold.api.resolveCaptureEvent(global.value.activeEvents,null,cold.h.auth.salesRep.default_event_id).id,'EV-123');cold.hooks.stop();});
 await test('B1.6 A cache hidden from B immediately',async f=>{await f.settle();f.h.online=false;f.h.auth={...f.h.auth,user:{authUserId:'B'},salesRep:{id:'rep-B',default_event_id:'EV-123'},authMode:'offline-restored'};f.render();assert.deepEqual(global.value.activeEvents,[]);await f.settle();assert.equal(global.value.selectedEvent,null);});
 await test('B1.8 default resolution, override priority, stale default and historical ID',async f=>{const list=[event(),event('override')];assert.equal(f.api.resolveCaptureEvent(list,null,'EV-123').id,'EV-123');assert.equal(f.api.resolveCaptureEvent(list,'override','EV-123').id,'override');assert.equal(f.api.resolveCaptureEvent(list,'missing','EV-123').id,'EV-123');assert.equal(f.api.resolveCaptureEvent(list,null,'missing').id,null);assert.equal(f.api.resolveCaptureEvent([],null,null,'historical').id,'historical');});
 await test('B1.9/10 reconnect refresh then failed refresh',async f=>{await f.settle();f.h.online=false;f.h.auth.authMode='offline-restored';await f.settle();f.h.list=[event('new')];f.h.online=true;f.h.auth.authMode='online';await f.settle();assert.equal(global.value.activeEvents[0].id,'new');f.h.queryError=Error('network');await global.value.refreshSelectedEvent();f.render();assert.equal(global.value.activeEvents[0].id,'new');});
 await test('B1.11 logout/switch invalidates delayed fetch',async f=>{const hold=defer();f.h.fetchHold=hold.promise;await f.settle();global.value.clearEvent();f.h.auth.user=null;f.h.auth.authMode='unauthenticated';f.render();hold.resolve({data:[event()],error:null});await f.settle();assert.deepEqual(global.value.activeEvents,[]);assert.equal(await f.api.loadEventCache('A'),null);});
 await test('B1.12 late cache read cannot replace fresh []',async f=>{const hold=defer();f.h.readHold=hold.promise;f.render();f.h.list=[];await global.value.refreshSelectedEvent();hold.resolve({ownerId:'A',schemaVersion:1,events:[event()]});await f.settle();assert.deepEqual(global.value.activeEvents,[]);});
 await test('B1.14 malformed cache ignored; unrelated data survives',async f=>{f.h.db.set('event_cacheA',{ownerId:'A',schemaVersion:1,events:[{id:'bad'}]});f.h.db.set('assetskeep',{id:'keep'});assert.equal(await f.api.loadEventCache('A'),null);assert(f.h.db.has('assetskeep'));});
 await test('B1.15 cache read failure does not prevent fetch/retry',async f=>{f.h.readError=true;await f.settle();assert.equal(global.value.activeEvents.length,1);f.h.readError=false;await global.value.refreshSelectedEvent();f.render();assert.equal(global.value.loadingEvent,false);});
 await test('B1.16 failed default read never writes fallback',async f=>{f.h.auth.salesRep.default_event_id='stale';f.h.repError=Error('network');await f.settle();assert.equal(f.h.updates.length,0);});
 await test('B1.17 concurrent refresh shares request',async f=>{await f.settle();const hold=defer();f.h.fetchHold=hold.promise;const count=f.h.fetches;const a=global.value.refreshSelectedEvent(),b=global.value.refreshSelectedEvent();assert.equal(a,b);hold.resolve({data:[],error:null});await a;assert.equal(f.h.fetches,count+1);});
 await test('B1.18 confirmed default changes preserve auth age',async f=>{f.h.db.set('auth_profilecurrent',{key:'current',schemaVersion:1,authUserId:'A',validatedAt:123,defaultEventId:'EV-123'});f.h.list=[event(),event('new')];await f.settle();await global.value.setSelectedEvent(event('new'));f.render();assert.equal(global.value.selectedEvent.id,'new');const cached=f.h.db.get('auth_profilecurrent');assert.equal(cached.defaultEventId,'new');assert.equal(cached.validatedAt,123);});
 await test('B1.19 rejected selection is not confirmed',async f=>{await f.settle();f.h.updateError=Error('denied');await assert.rejects(global.value.setSelectedEvent(event('new')));assert.equal(f.h.auth.salesRep.default_event_id,'EV-123');});
 await test('B1.21 failed cache commit keeps usable online list and releases guard',async f=>{f.h.writeError=true;await f.settle();assert.equal(global.value.activeEvents.length,1);assert.equal(global.value.loadingEvent,false);f.h.writeError=false;await global.value.refreshSelectedEvent();assert.equal((await f.api.loadEventCache('A')).length,1);});
 await test('B1.22 no-event draft survives storage round trip; write failure is surfaced',async f=>{const session={captureMethod:'MANUAL',sessionStatus:'CAPTURING',draftData:{clientName:'Preserved'},sync:{backendSessionId:'draft',backendAssetIds:{},backendExtractionIds:{}},createdAt:null,updatedAt:null};assert.equal(f.api.resolveCaptureEvent([],null,'stale').id,null);await f.api.saveDraftStrict(session,'A');assert.equal((await f.api.loadDraft('A')).draftData.clientName,'Preserved');assert.equal(await f.api.loadDraft('B'),null);f.h.writeError=true;await assert.rejects(f.api.saveDraftStrict(session,'A'));});
 await test('authoritative memory survives mode transition after cache write failure',async f=>{await f.settle();f.h.writeError=true;f.h.list=[];await global.value.refreshSelectedEvent();f.h.online=false;f.h.auth.authMode='offline-restored';await f.settle();assert.deepEqual(global.value.activeEvents,[]);});
 await test('owner switch invalidates fetch and restores only new owner cache',async f=>{const hold=defer();f.h.fetchHold=hold.promise;await f.settle();f.h.db.set('event_cacheB',{ownerId:'B',schemaVersion:1,events:[event('B-event')]});f.h.online=false;f.h.auth={...f.h.auth,user:{authUserId:'B'},salesRep:{id:'rep-B',default_event_id:'B-event'},authMode:'offline-restored'};await f.settle();hold.resolve({data:[event('A-event')],error:null});await f.settle();assert.equal(global.value.selectedEvent.id,'B-event');assert.equal(await f.api.loadEventCache('A'),null);});
 // Execute the production submission callback's no-event branch, with its real resolver/storage.
 const page=fs.readFileSync('src/CaptureLeadPage.tsx','utf8');
 const begin=page.indexOf('    const s    = sessionRef.current;',page.indexOf('const handleSaveAndNext ='));
 const end=page.indexOf('  }, [actions, form,',begin);
 assert(begin>0&&end>begin);
 const guardOut=path.join(dir,'guard.cjs');
 await esbuild.build({stdin:{contents:`export async function save(){const {sessionRef,form,actions,historicalEvent,resolveEvent,saveDraftStrict,authUserId,setPromotionToast}=globalThis.captureTest;${page.slice(begin,end)}}`,loader:'ts'},bundle:true,platform:'node',format:'cjs',outfile:guardOut});
 await test('B1.22 production save blocks no-event capture without reset and surfaces disk failure',async f=>{
  const session={captureMethod:'MANUAL',sessionStatus:'CAPTURING',draftData:{clientName:'Keep me'},sync:{backendSessionId:'held',backendAssetIds:{},backendExtractionIds:{}}};
  let resets=0;global.captureTest={sessionRef:{current:session},historicalEvent:{current:null},form:{handleReset(){resets++;}},actions:{resetSession(){resets++;}},resolveEvent:d=>f.api.resolveCaptureEvent([],d.captureEventId,'stale'),saveDraftStrict:f.api.saveDraftStrict,authUserId:'A',setPromotionToast(){}};
  const guard=require(guardOut);assert.match((await guard.save()).error,/kept as a draft/);assert.equal((await f.api.loadDraft('A')).draftData.clientName,'Keep me');assert.equal(resets,0);
  f.h.writeError=true;assert.match((await guard.save()).error,/Keep this capture open/);assert.equal(resets,0);
 });
 // Execute the actual version-upgrade callback against a v9 store inventory.
 const dbOut=path.join(dir,'db.cjs');await esbuild.build({entryPoints:['src/capture/db.ts'],bundle:true,platform:'node',format:'cjs',outfile:dbOut});
 const stores=new Set(['drafts','assets','pending_ops','lead_queue','completed_leads','auth_profile']);const created=[];let request,closed=0;
 const database={objectStoreNames:{contains:n=>stores.has(n)},createObjectStore(n,options){created.push([n,options]);stores.add(n);return {createIndex(){}};},close(){closed++;}};
 global.indexedDB={open(name,version){assert.equal(name,'capture_app');assert.equal(version,12);request={result:database,transaction:{objectStore:()=>({indexNames:{contains:()=>true}})}};return request;}};
 const dbApi=require(dbOut);const opened=dbApi.openDB();request.onupgradeneeded({oldVersion:9,target:request});request.onsuccess();assert.equal(await opened,database);assert.deepEqual(created,[['capture_config_cache',{keyPath:'key'}],['previous_rep_cache',{keyPath:'ownerId'}],['event_cache',{keyPath:'ownerId'}]]);assert.equal(stores.size,9);database.onversionchange();assert.equal(closed,1);
 const blocked=dbApi.openDB();request.onblocked();await assert.rejects(blocked,/blocked/);request.onsuccess();assert.equal(closed,2);passed++;console.log('PASS: B1.20 additive v9 migration, versionchange close and blocked-open recovery');
 console.log(`${passed} B1 checks passed`);
})().catch(e=>{console.error(e);process.exitCode=1;});
